### ISSUE TITLE
Login function

### ISSUE THREAD

**Issue by Musealo** [Musealo/capstone-project#12]
## Value Preposition

**As a User**..
**I need** a login function
**to be able to** save my data and play from any device

## Description

User logs in with Github

## Acceptance Criteria

- [x] On the Landing page is a sign in button
- [x] On click it redirects the user to the standard Github login page

## Tasks

- [x] Use next-auth to implement a Github log in function
