### ISSUE TITLE
CurrentFrivia Backend

### ISSUE THREAD

**Issue by Musealo** [Musealo/capstone-project#18]
## Value Preposition

**As a User**..
**I need** I want to see all current frivia from all players of my room
**to be able to** to read and answer them

## Description

Show each frivia in quiz cards on the page, including 4 buttons with the answers

## Acceptance Criteria

- [x] When a frivia is submitted it should be saved in the db and shown on the current frivia page
- [x] The user should be able to click on the answer buttons

## Tasks

- [x] onClick save the users answer in the backend 
- [x] Map through the questions to show them in cards
- [x] map through the submitted frivias array and pick the answer possibilities out including the boolean if they are true or false
