### ISSUE TITLE
AddFrivia Backend

### ISSUE THREAD

**Issue by Musealo** [Musealo/capstone-project#19]
## Value Preposition

**As a User**..
**I need** to "share" the added frivias
**to be able to** have other player answer them

## Description

When the user submits a new frivia it will be saved in the db with the question and an array including the value of the answers, the type and the boolean if the answer is true or false

## Acceptance Criteria

- [x] When the user submits their frivia it will be saved in the db
- [x] An array will be saved under the same _id including values of the answers and boolean

## Tasks

- [x] onSubmit create a new collection in the db which saves the questions as a string and an array with the answer possibilities and boolean
- [x] it should also save an empty string to later put the user answers in it to show it on the old frivia page
