### ISSUE TITLE
Invite player

### ISSUE THREAD

**Issue by Musealo** [Musealo/capstone-project#23]
## Value Preposition

**As a User**..
**I need**an option to invite other user
**to be able to** play with them

## Description

The user should be able to invite other players to play with them together

## Acceptance Criteria

- [x] Invite Player button

## Tasks

- [x] Create an invite player button in room menu
- [x] On click it will copy an invite link to the users clipboard
