### ISSUE TITLE
Join a room

### ISSUE THREAD

**Issue by Musealo** [Musealo/capstone-project#27]
## Value Preposition

**As a User**..
**I need** to be able to join a friends room 
**to be able to** play with them

## Description

After the log in on the landing page a join a room button will appear with a textfield in which the user puts the roomId they got from the owner of the room

## Acceptance Criteria

- [x] Show join a room button which opens a textfield in which the user puts the roomId 

## Tasks
- [x] Create a join room button
- [x] On click a text field will open in which the user can paste the room id
- [x] If the user put the ID in the textfield they press enter or a "join" button and they get redirected to the room with the fitting Id
