### ISSUE TITLE
Menu in a created room

### ISSUE THREAD

**Issue by Musealo** [Musealo/capstone-project#3]
## Value Preposition

**As a User**
**I need** a menu 
**to be able to** navigate through the different pages

## Description

Menu in the room with buttons for the user to navigate through the different pages of the room

## Acceptance Criteria

- [x] When on the room page it should show buttons to navigate through the different pages

## Tasks

- [x] Show a page with different buttons 
- [x] Back to landing page button
