### ISSUE TITLE
Create a room loading screen

### ISSUE THREAD

**Issue by Musealo** [Musealo/capstone-project#32]
## Value Preposition

**As a User**..
**I need** to see a loading screen when I create a room
**to be able to** to see what is happening and it doesn't feel like a lag

## Description

Show a screen with "Preparing Room..." when the user clicks on create a room

## Acceptance Criteria

- [x] When the user clicks on create a room show another page that tells the user whats happening

## Tasks

- [x] Update home.js 
- [x] When the user creates a room, show a loading screen that says "Preparing Room..." with a loading animation
