### ISSUE TITLE
Your Frivia Page

### ISSUE THREAD

**Issue by Musealo** [Musealo/capstone-project#36]
## Value Preposition

**As a User**..
**I need** a your frivia page
**to be able to** see the questions I asked in the room

## Description

Add a "Your frivia" page that shows the user what questions they asked in the room so far

## Acceptance Criteria

- [x]  Create a "Your frivia" button in the room menu
- [x]  On click show the "Your Frivia" page
- [x] The page should show all frivia the user created

## Tasks

- [x] In the api/frivia create a new if that checks if the parameter sent in comes from the your frivia page
- [x] if true then filter all frivia and check if the userId is equal to the userId sent from the request
- [x] In Frontend list all the filtered frivia
