### ISSUE TITLE
Current trivia button

### ISSUE THREAD

**Issue by Musealo** [Musealo/capstone-project#4]
## Value Preposition

**As a User**..
**I need** a current trivia button 
**to be able to** see the current trivia

## Description

Current Trivia button in the menu that on click brings the user to the current trivia page

## Acceptance Criteria

- [ ] When the current trivia button is clicked it will show the page with all current trivias

## Tasks

- [ ] Create a current trivia button
- [ ] On click the button opens the current trivia page of the room
- [ ] ...
