### ISSUE TITLE
Current trivias page

### ISSUE THREAD

**Issue by Musealo** [Musealo/capstone-project#5]
## Value Preposition

**As a User**..
**I need** the current trivia page
**to be able to** see and answer questions

## Description

User will see all current trivia questions, and the answer possibilities of each question

## Acceptance Criteria

- [x] When on the current trivia page it shows all current unanswered questions and possible answers

## Tasks

- [x] Show 4 buttons with the answers
- [x] The user can pick 1 of 4 answers
- [x] when answered the question will disappear from the current frivia page after 3 seconds
