### ISSUE TITLE
Old questions and answers

### ISSUE THREAD

**Issue by Musealo** [Musealo/capstone-project#7]
## Value Preposition

**As a User**..
**I need** to see the older questions and answer
**to be able to** review them whenever I want to

## Description

The user should see their answered frivia on the older frivia page

## Acceptance Criteria

- [x] When clicked on the older questions button, the page will open and show the old questions and answers
- [x] It also shows the highlighted answers 

## Tasks

- [x] Create a page that shows older questions 
- [x] On click it opens the older question page
- [x] Add the answered question of each individual user to their older trivia page

**Comment by dohoeppner** [comment]
Nur eine kleine Anmerkung: Vielleicht wäre die "Description" ein guter Platz kurz noch zu erläutern, wer genau wessen "older questions" sehen möchte/darf/soll (also einfach diesen Part des Spiels)?

**Comment by Musealo** [comment]
@dohoeppner danke hab ich erledigt
