### ISSUE TITLE
All Player page

### ISSUE THREAD

**Issue by Musealo** [Musealo/capstone-project#8]
## Value Preposition

**As a User**..
**I need** a page to see all players and a percentage of right answered questions
**to be able to** to see with whom I'm playing, and who answered the most question correctly

## Description

The user should see a page with all players of the current room so they know with whom they are playing

## Acceptance Criteria

- [x] Show a list of players in the room
- [x] Show the percantage of the correct answers

## Tasks

- [x] Create an all player button on the main menu
- [x] Create a all player page
- [x] Create a list that shows all players in the current room
- [x] Show in percent, how often a players answered correctly
