### ISSUE TITLE
Add new trivia

### ISSUE THREAD

**Issue by Musealo** [Musealo/capstone-project#9]
## Value Preposition

**As a User**..
**I need** an add new trivia page
**to be able to** make your friends answer them

## Description

Scribble / design or text

## Acceptance Criteria

- [x] When the create trivia button is clicked it will bring the user to the page
- [x] On the page it will show a text area in which the user can write its question
- [x] It will also have 4 fields in which the user can write their question
- [x] Checkbox to say what answer is right
- [x] Create a Form

## Tasks

- [x] Create a add trivia button
- [x] Create a add trivia page 
- [x] build a text area in which the user can ask its questions
- [x] build form component in which the user can write their answer choices
- [x] Create a checkbox for all answers so that the user can mark the correct answer
- [x] create a button to submit the questions and answers
- [x] Build a form component
